name: perfiman
description: Personal Finance Manager.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-144.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  logger: ^1.1.0
  google_fonts: ^2.2.0
  provider: ^6.0.2
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/purple_bg.jpg